FROM python:3.7-slim-bullseye
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /bot
COPY requirements.txt .
RUN apt-get update && apt-get -y install gcc \
    && python -m pip install --upgrade pip \
    && pip install -r requirements.txt
COPY *.py .
ENV TG_TOKEN=
ENV PRACTICUM_TOKEN=
ENV CHAT_ID=
RUN addgroup --system hwbot && adduser --system --group hwbot
USER hwbot
CMD ["python", "homework.py"]
